services:
  - type: web
    name: n8n
    env: node
    plan: free
    repo: https://github.com/n8n-io/n8n
    buildCommand: ""
    startCommand: npx n8n
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "tom"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Ts9192939495!"
